VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "pyconcrete-server"

  config.vm.provider "virtualbox" do |v|
    v.name = "pyconcrete_server_sandbox"
  end

  config.vm.synced_folder "../", "/home/pyconcrete"
  config.vm.provision :shell, path: "bootstrap.sh", args: $args, privileged: false

end
